paths:
  /categories:
    get:
      summary: دریافت لیست تمامی دسته‌بندی‌ها
      responses:
        '200':
          description: لیست دسته‌بندی‌ها بازیابی شد
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Category'
    post:
      summary: ایجاد دسته‌بندی جدید
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                thumbnail:
                  type: string
              required:
                - title
      responses:
        '201':
          description: دسته‌بندی با موفقیت ایجاد شد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 201
                  message:
                    type: string
                    example: 'Category created successfully'
                  categoryId:
                    type: integer
        '400':
          description: داده‌های ورودی نامعتبر است
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 400
                  errors:
                    type: array
                    items:
                      type: string
  /categories/{id}:
    get:
      summary: دریافت اطلاعات یک دسته‌بندی
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: شناسه دسته‌بندی
      responses:
        '200':
          description: دسته‌بندی یافت شد
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Category'
        '404':
          description: دسته‌بندی یافت نشد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: 'Category not found'
    put:
      summary: به‌روزرسانی اطلاعات یک دسته‌بندی
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: شناسه دسته‌بندی
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                thumbnail:
                  type: string
              required:
                - title
      responses:
        '200':
          description: دسته‌بندی با موفقیت به‌روزرسانی شد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Category updated successfully'
        '404':
          description: دسته‌بندی یافت نشد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: 'Category not found'
    delete:
      summary: حذف دسته‌بندی
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: شناسه دسته‌بندی
      responses:
        '200':
          description: دسته‌بندی با موفقیت حذف شد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 200
                  message:
                    type: string
                    example: 'Category deleted successfully'
        '404':
          description: دسته‌بندی یافت نشد
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: integer
                    example: 404
                  message:
                    type: string
                    example: 'Category not found'

components:
  schemas:
    Category:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        description:
          type: string
        thumbnail:
          type: string
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
